import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-200 min-h-screen flex flex-col justify-between items-center">
          <header className="">
            <Navbar />
          </header>
          <main className="w-3/4 pt-12 pb-20 flex-grow">
            {children}
          </main>
          <footer className="">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
